/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Code\\vuepress-starter\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-026a2cdb",
    path: "/Blog/Introduce/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-026a2cdb").then(next)
    },
  },
  {
    path: "/Blog/Introduce/index.html",
    redirect: "/Blog/Introduce/"
  },
  {
    path: "/01.Blog/01.Introduce.html",
    redirect: "/Blog/Introduce/"
  },
  {
    name: "v-6af2f6bb",
    path: "/Blog/build/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6af2f6bb").then(next)
    },
  },
  {
    path: "/Blog/build/index.html",
    redirect: "/Blog/build/"
  },
  {
    path: "/01.Blog/02.Build.html",
    redirect: "/Blog/build/"
  },
  {
    name: "v-6bcf5e5a",
    path: "/Blog/More/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bcf5e5a").then(next)
    },
  },
  {
    path: "/Blog/More/index.html",
    redirect: "/Blog/More/"
  },
  {
    path: "/01.Blog/03.More.html",
    redirect: "/Blog/More/"
  },
  {
    name: "v-2a0d135a",
    path: "/Blog/PicBed/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a0d135a").then(next)
    },
  },
  {
    path: "/Blog/PicBed/index.html",
    redirect: "/Blog/PicBed/"
  },
  {
    path: "/01.Blog/05.PicBed.html",
    redirect: "/Blog/PicBed/"
  },
  {
    name: "v-0ac604d3",
    path: "/Blog/DN/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ac604d3").then(next)
    },
  },
  {
    path: "/Blog/DN/index.html",
    redirect: "/Blog/DN/"
  },
  {
    path: "/01.Blog/04.DN.html",
    redirect: "/Blog/DN/"
  },
  {
    name: "v-0e7b15b3",
    path: "/Blog/Sync/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e7b15b3").then(next)
    },
  },
  {
    path: "/Blog/Sync/index.html",
    redirect: "/Blog/Sync/"
  },
  {
    path: "/01.Blog/06.Sync.html",
    redirect: "/Blog/Sync/"
  },
  {
    name: "v-4527aa9a",
    path: "/Blog/AutoDeploy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4527aa9a").then(next)
    },
  },
  {
    path: "/Blog/AutoDeploy/index.html",
    redirect: "/Blog/AutoDeploy/"
  },
  {
    path: "/01.Blog/07.AutoDeploy.html",
    redirect: "/Blog/AutoDeploy/"
  },
  {
    name: "v-202ccaad",
    path: "/pages/2e662a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-202ccaad").then(next)
    },
  },
  {
    path: "/pages/2e662a/index.html",
    redirect: "/pages/2e662a/"
  },
  {
    path: "/03.Git/01.Git.html",
    redirect: "/pages/2e662a/"
  },
  {
    name: "v-c739e29a",
    path: "/InterviewQ/INTV/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c739e29a").then(next)
    },
  },
  {
    path: "/InterviewQ/INTV/index.html",
    redirect: "/InterviewQ/INTV/"
  },
  {
    path: "/04.InterviewQ/01.INTV.html",
    redirect: "/InterviewQ/INTV/"
  },
  {
    name: "v-631db1d0",
    path: "/pages/f8a36c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-631db1d0").then(next)
    },
  },
  {
    path: "/pages/f8a36c/index.html",
    redirect: "/pages/f8a36c/"
  },
  {
    path: "/02.C++/01.C++方法.html",
    redirect: "/pages/f8a36c/"
  },
  {
    name: "v-42d2b6d6",
    path: "/InterviewQ/Java面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42d2b6d6").then(next)
    },
  },
  {
    path: "/InterviewQ/Java面试题/index.html",
    redirect: "/InterviewQ/Java面试题/"
  },
  {
    path: "/04.InterviewQ/02.Java面试题.html",
    redirect: "/InterviewQ/Java面试题/"
  },
  {
    name: "v-ecb78abe",
    path: "/InterviewQ/JVM面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ecb78abe").then(next)
    },
  },
  {
    path: "/InterviewQ/JVM面试题/index.html",
    redirect: "/InterviewQ/JVM面试题/"
  },
  {
    path: "/04.InterviewQ/04.JVM面试题.html",
    redirect: "/InterviewQ/JVM面试题/"
  },
  {
    name: "v-4d1a963e",
    path: "/InterviewQ/JUC面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d1a963e").then(next)
    },
  },
  {
    path: "/InterviewQ/JUC面试题/index.html",
    redirect: "/InterviewQ/JUC面试题/"
  },
  {
    path: "/04.InterviewQ/03.JUC面试题.html",
    redirect: "/InterviewQ/JUC面试题/"
  },
  {
    name: "v-e38c833e",
    path: "/InterviewQ/Linux面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e38c833e").then(next)
    },
  },
  {
    path: "/InterviewQ/Linux面试题/index.html",
    redirect: "/InterviewQ/Linux面试题/"
  },
  {
    path: "/04.InterviewQ/05.Linux面试题.html",
    redirect: "/InterviewQ/Linux面试题/"
  },
  {
    name: "v-27c01541",
    path: "/InterviewQ/SQL面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27c01541").then(next)
    },
  },
  {
    path: "/InterviewQ/SQL面试题/index.html",
    redirect: "/InterviewQ/SQL面试题/"
  },
  {
    path: "/04.InterviewQ/06.SQL面试题.html",
    redirect: "/InterviewQ/SQL面试题/"
  },
  {
    name: "v-958e28c6",
    path: "/InterviewQ/Spring面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-958e28c6").then(next)
    },
  },
  {
    path: "/InterviewQ/Spring面试题/index.html",
    redirect: "/InterviewQ/Spring面试题/"
  },
  {
    path: "/04.InterviewQ/09.Spring面试题.html",
    redirect: "/InterviewQ/Spring面试题/"
  },
  {
    name: "v-30f56101",
    path: "/InterviewQ/Maven/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30f56101").then(next)
    },
  },
  {
    path: "/InterviewQ/Maven/index.html",
    redirect: "/InterviewQ/Maven/"
  },
  {
    path: "/04.InterviewQ/07.Maven面试题.html",
    redirect: "/InterviewQ/Maven/"
  },
  {
    name: "v-e595833e",
    path: "/InterviewQ/MyBatis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e595833e").then(next)
    },
  },
  {
    path: "/InterviewQ/MyBatis/index.html",
    redirect: "/InterviewQ/MyBatis/"
  },
  {
    path: "/04.InterviewQ/08.MyBatis面试题.html",
    redirect: "/InterviewQ/MyBatis/"
  },
  {
    name: "v-2fa7fe01",
    path: "/InterviewQ/Redis面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fa7fe01").then(next)
    },
  },
  {
    path: "/InterviewQ/Redis面试题/index.html",
    redirect: "/InterviewQ/Redis面试题/"
  },
  {
    path: "/04.InterviewQ/10.Redis面试题.html",
    redirect: "/InterviewQ/Redis面试题/"
  },
  {
    name: "v-d917335a",
    path: "/InterviewQ/Algorithm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d917335a").then(next)
    },
  },
  {
    path: "/InterviewQ/Algorithm/index.html",
    redirect: "/InterviewQ/Algorithm/"
  },
  {
    path: "/04.InterviewQ/11.Algorithm.html",
    redirect: "/InterviewQ/Algorithm/"
  },
  {
    name: "v-dd6c0f46",
    path: "/InterviewQ/Login/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dd6c0f46").then(next)
    },
  },
  {
    path: "/InterviewQ/Login/index.html",
    redirect: "/InterviewQ/Login/"
  },
  {
    path: "/04.InterviewQ/12.Login.html",
    redirect: "/InterviewQ/Login/"
  },
  {
    name: "v-a8b7029a",
    path: "/pages/5f620a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8b7029a").then(next)
    },
  },
  {
    path: "/pages/5f620a/index.html",
    redirect: "/pages/5f620a/"
  },
  {
    path: "/05.Java/01.Java.html",
    redirect: "/pages/5f620a/"
  },
  {
    name: "v-417f3b4b",
    path: "/pages/777f5e/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-417f3b4b").then(next)
    },
  },
  {
    path: "/pages/777f5e/index.html",
    redirect: "/pages/777f5e/"
  },
  {
    path: "/05.Java/03.JVM.html",
    redirect: "/pages/777f5e/"
  },
  {
    name: "v-eeb5098a",
    path: "/Life/Learn/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eeb5098a").then(next)
    },
  },
  {
    path: "/Life/Learn/index.html",
    redirect: "/Life/Learn/"
  },
  {
    path: "/06.Life/01.Learn.html",
    redirect: "/Life/Learn/"
  },
  {
    name: "v-8ba3a0c2",
    path: "/pages/eec04e/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ba3a0c2").then(next)
    },
  },
  {
    path: "/pages/eec04e/index.html",
    redirect: "/pages/eec04e/"
  },
  {
    path: "/05.Java/02.JUC.html",
    redirect: "/pages/eec04e/"
  },
  {
    name: "v-eee68fa6",
    path: "/pages/bd79a7/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eee68fa6").then(next)
    },
  },
  {
    path: "/pages/bd79a7/index.html",
    redirect: "/pages/bd79a7/"
  },
  {
    path: "/08.MicroServices/04.Dubbo.html",
    redirect: "/pages/bd79a7/"
  },
  {
    name: "v-5059f7fe",
    path: "/pages/6d69d7/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5059f7fe").then(next)
    },
  },
  {
    path: "/pages/6d69d7/index.html",
    redirect: "/pages/6d69d7/"
  },
  {
    path: "/05.Java/04.反射&动态代理.html",
    redirect: "/pages/6d69d7/"
  },
  {
    name: "v-fc6c8ae6",
    path: "/pages/427068/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fc6c8ae6").then(next)
    },
  },
  {
    path: "/pages/427068/index.html",
    redirect: "/pages/427068/"
  },
  {
    path: "/08.MicroServices/01.MicroServices.html",
    redirect: "/pages/427068/"
  },
  {
    name: "v-4ff8ceea",
    path: "/pages/16ebf4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ff8ceea").then(next)
    },
  },
  {
    path: "/pages/16ebf4/index.html",
    redirect: "/pages/16ebf4/"
  },
  {
    path: "/08.MicroServices/02.RabbitMQ.html",
    redirect: "/pages/16ebf4/"
  },
  {
    name: "v-6ab94649",
    path: "/pages/e01785/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ab94649").then(next)
    },
  },
  {
    path: "/pages/e01785/index.html",
    redirect: "/pages/e01785/"
  },
  {
    path: "/08.MicroServices/03.Docker.html",
    redirect: "/pages/e01785/"
  },
  {
    name: "v-9474a4e6",
    path: "/pages/75426d/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9474a4e6").then(next)
    },
  },
  {
    path: "/pages/75426d/index.html",
    redirect: "/pages/75426d/"
  },
  {
    path: "/08.MicroServices/05.MongoDB.html",
    redirect: "/pages/75426d/"
  },
  {
    name: "v-3a0063ad",
    path: "/pages/7839e5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a0063ad").then(next)
    },
  },
  {
    path: "/pages/7839e5/index.html",
    redirect: "/pages/7839e5/"
  },
  {
    path: "/08.MicroServices/06.Zookeeper.html",
    redirect: "/pages/7839e5/"
  },
  {
    name: "v-08220c74",
    path: "/Redis/Redis安装/Win/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08220c74").then(next)
    },
  },
  {
    path: "/Redis/Redis安装/Win/index.html",
    redirect: "/Redis/Redis安装/Win/"
  },
  {
    path: "/10.Redis/01.Redis安装/01.Redis安装.html",
    redirect: "/Redis/Redis安装/Win/"
  },
  {
    name: "v-9e397966",
    path: "/Reids/Redis安装/Linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e397966").then(next)
    },
  },
  {
    path: "/Reids/Redis安装/Linux/index.html",
    redirect: "/Reids/Redis安装/Linux/"
  },
  {
    path: "/10.Redis/01.Redis安装/02.Linux.html",
    redirect: "/Reids/Redis安装/Linux/"
  },
  {
    name: "v-48f6742d",
    path: "/pages/767b46/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48f6742d").then(next)
    },
  },
  {
    path: "/pages/767b46/index.html",
    redirect: "/pages/767b46/"
  },
  {
    path: "/09.MySQL/01.MySQL.html",
    redirect: "/pages/767b46/"
  },
  {
    name: "v-2d5edf7b",
    path: "/pages/83183b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d5edf7b").then(next)
    },
  },
  {
    path: "/pages/83183b/index.html",
    redirect: "/pages/83183b/"
  },
  {
    path: "/10.Redis/02.Redis基础.html",
    redirect: "/pages/83183b/"
  },
  {
    name: "v-96d8cf86",
    path: "/pages/6b727a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-96d8cf86").then(next)
    },
  },
  {
    path: "/pages/6b727a/index.html",
    redirect: "/pages/6b727a/"
  },
  {
    path: "/10.Redis/04.Redis集群安装.html",
    redirect: "/pages/6b727a/"
  },
  {
    name: "v-663869a2",
    path: "/pages/f302c3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-663869a2").then(next)
    },
  },
  {
    path: "/pages/f302c3/index.html",
    redirect: "/pages/f302c3/"
  },
  {
    path: "/10.Redis/03.Redis实战.html",
    redirect: "/pages/f302c3/"
  },
  {
    name: "v-6c489d60",
    path: "/pages/97d2c6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c489d60").then(next)
    },
  },
  {
    path: "/pages/97d2c6/index.html",
    redirect: "/pages/97d2c6/"
  },
  {
    path: "/10.Redis/05.Redis分布式缓存.html",
    redirect: "/pages/97d2c6/"
  },
  {
    name: "v-c8a5cf8c",
    path: "/pages/c7ec43/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c8a5cf8c").then(next)
    },
  },
  {
    path: "/pages/c7ec43/index.html",
    redirect: "/pages/c7ec43/"
  },
  {
    path: "/10.Redis/06.Redis多级缓存.html",
    redirect: "/pages/c7ec43/"
  },
  {
    name: "v-9f5e32aa",
    path: "/pages/e81cee/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f5e32aa").then(next)
    },
  },
  {
    path: "/pages/e81cee/index.html",
    redirect: "/pages/e81cee/"
  },
  {
    path: "/10.Redis/07.Redis原理.html",
    redirect: "/pages/e81cee/"
  },
  {
    name: "v-1157bebe",
    path: "/pages/5c3702/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1157bebe").then(next)
    },
  },
  {
    path: "/pages/5c3702/index.html",
    redirect: "/pages/5c3702/"
  },
  {
    path: "/10.Redis/08.案例导入说明.html",
    redirect: "/pages/5c3702/"
  },
  {
    name: "v-dbf39936",
    path: "/Computer/Linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dbf39936").then(next)
    },
  },
  {
    path: "/Computer/Linux/index.html",
    redirect: "/Computer/Linux/"
  },
  {
    path: "/11.Computer/01.Linux.html",
    redirect: "/Computer/Linux/"
  },
  {
    name: "v-ca99173c",
    path: "/pages/0459ad/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca99173c").then(next)
    },
  },
  {
    path: "/pages/0459ad/index.html",
    redirect: "/pages/0459ad/"
  },
  {
    path: "/10.Redis/09.安装OpenResty.html",
    redirect: "/pages/0459ad/"
  },
  {
    name: "v-03357bf9",
    path: "/pages/6de838/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03357bf9").then(next)
    },
  },
  {
    path: "/pages/6de838/index.html",
    redirect: "/pages/6de838/"
  },
  {
    path: "/12.SpringBoot/01.big-event.html",
    redirect: "/pages/6de838/"
  },
  {
    name: "v-2a143353",
    path: "/pages/7dc24f/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a143353").then(next)
    },
  },
  {
    path: "/pages/7dc24f/index.html",
    redirect: "/pages/7dc24f/"
  },
  {
    path: "/11.Computer/01.SoftwareTest.html",
    redirect: "/pages/7dc24f/"
  },
  {
    name: "v-48d11354",
    path: "/pages/651745/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48d11354").then(next)
    },
  },
  {
    path: "/pages/651745/index.html",
    redirect: "/pages/651745/"
  },
  {
    path: "/12.SpringBoot/04.Spring注解.html",
    redirect: "/pages/651745/"
  },
  {
    name: "v-b3797e00",
    path: "/pages/e27777/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3797e00").then(next)
    },
  },
  {
    path: "/pages/e27777/index.html",
    redirect: "/pages/e27777/"
  },
  {
    path: "/12.SpringBoot/05.数据库设计文档.html",
    redirect: "/pages/e27777/"
  },
  {
    name: "v-e966c23e",
    path: "/pages/cde4de/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e966c23e").then(next)
    },
  },
  {
    path: "/pages/cde4de/index.html",
    redirect: "/pages/cde4de/"
  },
  {
    path: "/13.SSM/01.Spring.html",
    redirect: "/pages/cde4de/"
  },
  {
    name: "v-0133d33f",
    path: "/pages/73b0ae/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0133d33f").then(next)
    },
  },
  {
    path: "/pages/73b0ae/index.html",
    redirect: "/pages/73b0ae/"
  },
  {
    path: "/13.SSM/02.SpringBoot.html",
    redirect: "/pages/73b0ae/"
  },
  {
    name: "v-080c2ce6",
    path: "/pages/1fa27c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-080c2ce6").then(next)
    },
  },
  {
    path: "/pages/1fa27c/index.html",
    redirect: "/pages/1fa27c/"
  },
  {
    path: "/13.SSM/03.MyBatis.html",
    redirect: "/pages/1fa27c/"
  },
  {
    name: "v-3a699613",
    path: "/pages/c0269b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a699613").then(next)
    },
  },
  {
    path: "/pages/c0269b/index.html",
    redirect: "/pages/c0269b/"
  },
  {
    path: "/12.SpringBoot/03.sky-take-out2.html",
    redirect: "/pages/c0269b/"
  },
  {
    name: "v-6e6ef9f3",
    path: "/pages/1e2d53/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e6ef9f3").then(next)
    },
  },
  {
    path: "/pages/1e2d53/index.html",
    redirect: "/pages/1e2d53/"
  },
  {
    path: "/12.SpringBoot/02.sky-take-out.html",
    redirect: "/pages/1e2d53/"
  },
  {
    name: "v-277c682c",
    path: "/pages/47e1e8/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-277c682c").then(next)
    },
  },
  {
    path: "/pages/47e1e8/index.html",
    redirect: "/pages/47e1e8/"
  },
  {
    path: "/14.Work/01.idea快捷键.html",
    redirect: "/pages/47e1e8/"
  },
  {
    name: "v-9656075a",
    path: "/pages/b8f6a1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9656075a").then(next)
    },
  },
  {
    path: "/pages/b8f6a1/index.html",
    redirect: "/pages/b8f6a1/"
  },
  {
    path: "/14.Work/03.Sql.html",
    redirect: "/pages/b8f6a1/"
  },
  {
    name: "v-1ee99ef1",
    path: "/pages/a1a8a7/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ee99ef1").then(next)
    },
  },
  {
    path: "/pages/a1a8a7/index.html",
    redirect: "/pages/a1a8a7/"
  },
  {
    path: "/14.Work/04.项目搭建.html",
    redirect: "/pages/a1a8a7/"
  },
  {
    name: "v-1c11e32d",
    path: "/pages/6f5b27/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c11e32d").then(next)
    },
  },
  {
    path: "/pages/6f5b27/index.html",
    redirect: "/pages/6f5b27/"
  },
  {
    path: "/13.SSM/04.MyBatisPlus.html",
    redirect: "/pages/6f5b27/"
  },
  {
    name: "v-2732075a",
    path: "/pages/f2ef46/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2732075a").then(next)
    },
  },
  {
    path: "/pages/f2ef46/index.html",
    redirect: "/pages/f2ef46/"
  },
  {
    path: "/14.Work/02.Secure.html",
    redirect: "/pages/f2ef46/"
  },
  {
    name: "v-0343b8e6",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0343b8e6").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-75116ca6",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75116ca6").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-63e8a84a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63e8a84a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-d1ba87a6",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1ba87a6").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]