/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Code\\vuepress-starter\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-026a2cdb",
    path: "/Blog/Introduce/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-026a2cdb").then(next)
    },
  },
  {
    path: "/Blog/Introduce/index.html",
    redirect: "/Blog/Introduce/"
  },
  {
    path: "/01.Blog/01.Introduce.html",
    redirect: "/Blog/Introduce/"
  },
  {
    name: "v-3f56744d",
    path: "/Blog/Qiniu/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f56744d").then(next)
    },
  },
  {
    path: "/Blog/Qiniu/index.html",
    redirect: "/Blog/Qiniu/"
  },
  {
    path: "/01.Blog/05.Qiniu.html",
    redirect: "/Blog/Qiniu/"
  },
  {
    name: "v-6af2f6bb",
    path: "/Blog/build/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6af2f6bb").then(next)
    },
  },
  {
    path: "/Blog/build/index.html",
    redirect: "/Blog/build/"
  },
  {
    path: "/01.Blog/02.Build.html",
    redirect: "/Blog/build/"
  },
  {
    name: "v-0ac604d3",
    path: "/Blog/DN/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ac604d3").then(next)
    },
  },
  {
    path: "/Blog/DN/index.html",
    redirect: "/Blog/DN/"
  },
  {
    path: "/01.Blog/04.DN.html",
    redirect: "/Blog/DN/"
  },
  {
    name: "v-6bcf5e5a",
    path: "/Blog/More/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bcf5e5a").then(next)
    },
  },
  {
    path: "/Blog/More/index.html",
    redirect: "/Blog/More/"
  },
  {
    path: "/01.Blog/03.More.html",
    redirect: "/Blog/More/"
  },
  {
    name: "v-4527aa9a",
    path: "/Blog/AutoDeploy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4527aa9a").then(next)
    },
  },
  {
    path: "/Blog/AutoDeploy/index.html",
    redirect: "/Blog/AutoDeploy/"
  },
  {
    path: "/01.Blog/07.AutoDeploy.html",
    redirect: "/Blog/AutoDeploy/"
  },
  {
    name: "v-0e7b15b3",
    path: "/Blog/Sync/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e7b15b3").then(next)
    },
  },
  {
    path: "/Blog/Sync/index.html",
    redirect: "/Blog/Sync/"
  },
  {
    path: "/01.Blog/06.Sync.html",
    redirect: "/Blog/Sync/"
  },
  {
    name: "v-631db1d0",
    path: "/pages/f8a36c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-631db1d0").then(next)
    },
  },
  {
    path: "/pages/f8a36c/index.html",
    redirect: "/pages/f8a36c/"
  },
  {
    path: "/02.C++/01.C++方法.html",
    redirect: "/pages/f8a36c/"
  },
  {
    name: "v-202ccaad",
    path: "/pages/2e662a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-202ccaad").then(next)
    },
  },
  {
    path: "/pages/2e662a/index.html",
    redirect: "/pages/2e662a/"
  },
  {
    path: "/03.Git/01.Git.html",
    redirect: "/pages/2e662a/"
  },
  {
    name: "v-cd328d1a",
    path: "/InterviewQ/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd328d1a").then(next)
    },
  },
  {
    path: "/InterviewQ/Java/index.html",
    redirect: "/InterviewQ/Java/"
  },
  {
    path: "/04.InterviewQ/02.Java.html",
    redirect: "/InterviewQ/Java/"
  },
  {
    name: "v-c739e29a",
    path: "/InterviewQ/INTV/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c739e29a").then(next)
    },
  },
  {
    path: "/InterviewQ/INTV/index.html",
    redirect: "/InterviewQ/INTV/"
  },
  {
    path: "/04.InterviewQ/01.INTV.html",
    redirect: "/InterviewQ/INTV/"
  },
  {
    name: "v-071e3c0a",
    path: "/InterviewQ/JUC/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-071e3c0a").then(next)
    },
  },
  {
    path: "/InterviewQ/JUC/index.html",
    redirect: "/InterviewQ/JUC/"
  },
  {
    path: "/04.InterviewQ/03.JUC.html",
    redirect: "/InterviewQ/JUC/"
  },
  {
    name: "v-e10f75b2",
    path: "/InterviewQ/JVM/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e10f75b2").then(next)
    },
  },
  {
    path: "/InterviewQ/JVM/index.html",
    redirect: "/InterviewQ/JVM/"
  },
  {
    path: "/04.InterviewQ/04.JVM.html",
    redirect: "/InterviewQ/JVM/"
  },
  {
    name: "v-7904caff",
    path: "/InterviewQ/Linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7904caff").then(next)
    },
  },
  {
    path: "/InterviewQ/Linux/index.html",
    redirect: "/InterviewQ/Linux/"
  },
  {
    path: "/04.InterviewQ/05.Linux.html",
    redirect: "/InterviewQ/Linux/"
  },
  {
    name: "v-210a26ee",
    path: "/InterviewQ/SQL/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-210a26ee").then(next)
    },
  },
  {
    path: "/InterviewQ/SQL/index.html",
    redirect: "/InterviewQ/SQL/"
  },
  {
    path: "/04.InterviewQ/06.SQL.html",
    redirect: "/InterviewQ/SQL/"
  },
  {
    name: "v-73e1a14d",
    path: "/InterviewQ/Maven/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73e1a14d").then(next)
    },
  },
  {
    path: "/InterviewQ/Maven/index.html",
    redirect: "/InterviewQ/Maven/"
  },
  {
    path: "/04.InterviewQ/07.Maven.html",
    redirect: "/InterviewQ/Maven/"
  },
  {
    name: "v-4416917b",
    path: "/InterviewQ/MyBatis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4416917b").then(next)
    },
  },
  {
    path: "/InterviewQ/MyBatis/index.html",
    redirect: "/InterviewQ/MyBatis/"
  },
  {
    path: "/04.InterviewQ/08.MyBatis.html",
    redirect: "/InterviewQ/MyBatis/"
  },
  {
    name: "v-4fb26793",
    path: "/pages/896da2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fb26793").then(next)
    },
  },
  {
    path: "/pages/896da2/index.html",
    redirect: "/pages/896da2/"
  },
  {
    path: "/04.InterviewQ/09.SpringHome.html",
    redirect: "/pages/896da2/"
  },
  {
    name: "v-d917335a",
    path: "/InterviewQ/Algorithm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d917335a").then(next)
    },
  },
  {
    path: "/InterviewQ/Algorithm/index.html",
    redirect: "/InterviewQ/Algorithm/"
  },
  {
    path: "/04.InterviewQ/11.Algorithm.html",
    redirect: "/InterviewQ/Algorithm/"
  },
  {
    name: "v-25c8413d",
    path: "/InterviewQ/Redis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25c8413d").then(next)
    },
  },
  {
    path: "/InterviewQ/Redis/index.html",
    redirect: "/InterviewQ/Redis/"
  },
  {
    path: "/04.InterviewQ/10.Redis.html",
    redirect: "/InterviewQ/Redis/"
  },
  {
    name: "v-dd6c0f46",
    path: "/InterviewQ/Login/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dd6c0f46").then(next)
    },
  },
  {
    path: "/InterviewQ/Login/index.html",
    redirect: "/InterviewQ/Login/"
  },
  {
    path: "/04.InterviewQ/12.Login.html",
    redirect: "/InterviewQ/Login/"
  },
  {
    name: "v-a8b7029a",
    path: "/pages/5f620a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8b7029a").then(next)
    },
  },
  {
    path: "/pages/5f620a/index.html",
    redirect: "/pages/5f620a/"
  },
  {
    path: "/05.Java/01.Java.html",
    redirect: "/pages/5f620a/"
  },
  {
    name: "v-417f3b4b",
    path: "/pages/777f5e/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-417f3b4b").then(next)
    },
  },
  {
    path: "/pages/777f5e/index.html",
    redirect: "/pages/777f5e/"
  },
  {
    path: "/05.Java/03.JVM.html",
    redirect: "/pages/777f5e/"
  },
  {
    name: "v-5059f7fe",
    path: "/pages/6d69d7/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5059f7fe").then(next)
    },
  },
  {
    path: "/pages/6d69d7/index.html",
    redirect: "/pages/6d69d7/"
  },
  {
    path: "/05.Java/04.反射&动态代理.html",
    redirect: "/pages/6d69d7/"
  },
  {
    name: "v-eedbe766",
    path: "/pages/c70e3b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eedbe766").then(next)
    },
  },
  {
    path: "/pages/c70e3b/index.html",
    redirect: "/pages/c70e3b/"
  },
  {
    path: "/06.Learn/01.Learn.html",
    redirect: "/pages/c70e3b/"
  },
  {
    name: "v-8ba3a0c2",
    path: "/pages/eec04e/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ba3a0c2").then(next)
    },
  },
  {
    path: "/pages/eec04e/index.html",
    redirect: "/pages/eec04e/"
  },
  {
    path: "/05.Java/02.JUC.html",
    redirect: "/pages/eec04e/"
  },
  {
    name: "v-3c0876ed",
    path: "/pages/29ecf5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c0876ed").then(next)
    },
  },
  {
    path: "/pages/29ecf5/index.html",
    redirect: "/pages/29ecf5/"
  },
  {
    path: "/07.Linux/01.Linux.html",
    redirect: "/pages/29ecf5/"
  },
  {
    name: "v-d1ba87a6",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1ba87a6").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-0343b8e6",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0343b8e6").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-75116ca6",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75116ca6").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-63e8a84a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63e8a84a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]