/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "TypeScript4 文档",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "https://img.cyanyep.top/Blog/Snipaste_2025-02-11_20-04-18.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "零成本搭建个人博客网站",
      "frontmatter": {
        "title": "零成本搭建个人博客网站",
        "date": "2025-01-16T21:10:33.000Z",
        "permalink": "/Blog/Introduce/",
        "categories": [
          "Blog"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/01.Blog/01.Introduce.html",
      "relativePath": "01.Blog/01.Introduce.md",
      "key": "v-026a2cdb",
      "path": "/Blog/Introduce/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "你需要会什么",
          "slug": "你需要会什么"
        },
        {
          "level": 2,
          "title": "你需要付出什么",
          "slug": "你需要付出什么"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "图床",
      "frontmatter": {
        "title": "图床",
        "date": "2025-03-26T21:10:33.000Z",
        "permalink": "/Blog/Qiniu/",
        "categories": [
          "Blog"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/01.Blog/05.Qiniu.html",
      "relativePath": "01.Blog/05.Qiniu.md",
      "key": "v-3f56744d",
      "path": "/Blog/Qiniu/",
      "headers": [
        {
          "level": 2,
          "title": "图片上传工具",
          "slug": "图片上传工具"
        },
        {
          "level": 2,
          "title": "为图床设置自己的域名",
          "slug": "为图床设置自己的域名"
        },
        {
          "level": 3,
          "title": "添加子域名",
          "slug": "添加子域名"
        },
        {
          "level": 3,
          "title": "将阿里云的证书添加到七牛云",
          "slug": "将阿里云的证书添加到七牛云"
        },
        {
          "level": 3,
          "title": "在七牛云添加域名",
          "slug": "在七牛云添加域名"
        },
        {
          "level": 3,
          "title": "将子域名解析到七牛云",
          "slug": "将子域名解析到七牛云"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "从零开始搭建博客",
      "frontmatter": {
        "title": "从零开始搭建博客",
        "date": "2025-01-17T21:10:33.000Z",
        "permalink": "/Blog/build/",
        "categories": [
          "Blog"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/01.Blog/02.Build.html",
      "relativePath": "01.Blog/02.Build.md",
      "key": "v-6af2f6bb",
      "path": "/Blog/build/",
      "headers": [
        {
          "level": 2,
          "title": "本地搭建",
          "slug": "本地搭建"
        },
        {
          "level": 2,
          "title": "优化",
          "slug": "优化"
        },
        {
          "level": 3,
          "title": "配置首页",
          "slug": "配置首页"
        },
        {
          "level": 3,
          "title": "热更新",
          "slug": "热更新"
        },
        {
          "level": 3,
          "title": "导航栏配置",
          "slug": "导航栏配置"
        },
        {
          "level": 3,
          "title": "静态资源",
          "slug": "静态资源"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 3,
          "title": "博客准备",
          "slug": "博客准备"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "自动生成 front matter",
          "slug": "自动生成-front-matter"
        },
        {
          "level": 2,
          "title": "插件",
          "slug": "插件"
        },
        {
          "level": 3,
          "title": "vuepress-plugin-code-copy",
          "slug": "vuepress-plugin-code-copy"
        },
        {
          "level": 3,
          "title": "reading-progress",
          "slug": "reading-progress"
        },
        {
          "level": 3,
          "title": "cursor-effects",
          "slug": "cursor-effects"
        },
        {
          "level": 3,
          "title": "vuepress-plugin-dynamic-title",
          "slug": "vuepress-plugin-dynamic-title"
        },
        {
          "level": 2,
          "title": "部署",
          "slug": "部署"
        }
      ],
      "lastUpdated": "2025/3/28 15:37:45",
      "lastUpdatedTimestamp": 1743147465000
    },
    {
      "title": "域名",
      "frontmatter": {
        "title": "域名",
        "date": "2025-03-26T17:10:33.000Z",
        "permalink": "/Blog/DN/",
        "categories": [
          "Blog"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/01.Blog/04.DN.html",
      "relativePath": "01.Blog/04.DN.md",
      "key": "v-0ac604d3",
      "path": "/Blog/DN/",
      "headers": [
        {
          "level": 2,
          "title": "购买域名",
          "slug": "购买域名"
        },
        {
          "level": 2,
          "title": "域名解析",
          "slug": "域名解析"
        },
        {
          "level": 2,
          "title": "域名解析完善",
          "slug": "域名解析完善"
        }
      ],
      "lastUpdated": "2025/3/28 15:37:45",
      "lastUpdatedTimestamp": 1743147465000
    },
    {
      "title": "更多配置",
      "frontmatter": {
        "title": "更多配置",
        "date": "2025-03-26T17:10:33.000Z",
        "permalink": "/Blog/More/",
        "categories": [
          "Blog"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/01.Blog/03.More.html",
      "relativePath": "01.Blog/03.More.md",
      "key": "v-6bcf5e5a",
      "path": "/Blog/More/",
      "headers": [
        {
          "level": 2,
          "title": "最后更新时间",
          "slug": "最后更新时间"
        },
        {
          "level": 2,
          "title": "Git 仓库和编辑链接",
          "slug": "git-仓库和编辑链接"
        },
        {
          "level": 2,
          "title": "footer",
          "slug": "footer"
        },
        {
          "level": 2,
          "title": "分离配置",
          "slug": "分离配置"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "自动部署",
      "frontmatter": {
        "title": "自动部署",
        "date": "2025-03-28T11:10:33.000Z",
        "permalink": "/Blog/AutoDeploy/",
        "categories": [
          "Blog"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/01.Blog/07.AutoDeploy.html",
      "relativePath": "01.Blog/07.AutoDeploy.md",
      "key": "v-4527aa9a",
      "path": "/Blog/AutoDeploy/",
      "headers": [
        {
          "level": 2,
          "title": "通过Github Action自动构建并部署项目",
          "slug": "通过github-action自动构建并部署项目"
        },
        {
          "level": 2,
          "title": "优化自动部署",
          "slug": "优化自动部署"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "同步GitHub和Gitee",
      "frontmatter": {
        "title": "同步GitHub和Gitee",
        "date": "2025-03-27T11:10:33.000Z",
        "permalink": "/Blog/Sync/",
        "categories": [
          "Blog"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/01.Blog/06.Sync.html",
      "relativePath": "01.Blog/06.Sync.md",
      "key": "v-0e7b15b3",
      "path": "/Blog/Sync/",
      "headers": [
        {
          "level": 2,
          "title": "手动同步",
          "slug": "手动同步"
        },
        {
          "level": 2,
          "title": "推送两个仓库",
          "slug": "推送两个仓库"
        },
        {
          "level": 2,
          "title": "Github Actions 自动同步（推荐使用）",
          "slug": "github-actions-自动同步-推荐使用"
        },
        {
          "level": 3,
          "title": "同步仓库具体操作",
          "slug": "同步仓库具体操作"
        },
        {
          "level": 3,
          "title": "Gitee 自动部署 Pages（！！Gitee Pages目前停止服务，以下操作已无效）",
          "slug": "gitee-自动部署-pages-gitee-pages目前停止服务-以下操作已无效"
        }
      ],
      "lastUpdated": "2025/3/28 15:37:45",
      "lastUpdatedTimestamp": 1743147465000
    },
    {
      "title": "C++方法",
      "frontmatter": {
        "title": "C++方法",
        "date": "2025-03-17T11:12:20.000Z",
        "permalink": "/pages/f8a36c/",
        "categories": [
          "C++"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/02.C++/01.C++%E6%96%B9%E6%B3%95.html",
      "relativePath": "02.C++/01.C++方法.md",
      "key": "v-631db1d0",
      "path": "/pages/f8a36c/",
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "Git",
      "frontmatter": {
        "title": "Git",
        "date": "2025-01-20T22:11:45.000Z",
        "permalink": "/pages/2e662a/",
        "categories": [
          "Git"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/03.Git/01.Git.html",
      "relativePath": "03.Git/01.Git.md",
      "key": "v-202ccaad",
      "path": "/pages/2e662a/",
      "headers": [
        {
          "level": 2,
          "title": "2.1、开发中的实际场景",
          "slug": "_2-1、开发中的实际场景"
        },
        {
          "level": 2,
          "title": "2.2、版本控制器的方式*",
          "slug": "_2-2、版本控制器的方式"
        },
        {
          "level": 2,
          "title": "2.3、SVN",
          "slug": "_2-3、svn"
        },
        {
          "level": 2,
          "title": "2.4、Git",
          "slug": "_2-4、git"
        },
        {
          "level": 2,
          "title": "2.5、Git工作流程图**",
          "slug": "_2-5、git工作流程图"
        },
        {
          "level": 2,
          "title": "3.1、Git环境配置",
          "slug": "_3-1、git环境配置"
        },
        {
          "level": 3,
          "title": "3.1.1下载与安装",
          "slug": "_3-1-1下载与安装"
        },
        {
          "level": 3,
          "title": "3.1.2基本配置",
          "slug": "_3-1-2基本配置"
        },
        {
          "level": 3,
          "title": "3.1.3为常用指令配置别名（可选）",
          "slug": "_3-1-3为常用指令配置别名-可选"
        },
        {
          "level": 3,
          "title": "3.1.4解决GitBash乱码问题",
          "slug": "_3-1-4解决gitbash乱码问题"
        },
        {
          "level": 2,
          "title": "3.2、获取本地仓库",
          "slug": "_3-2、获取本地仓库"
        },
        {
          "level": 2,
          "title": "3.3、基础操作指令**",
          "slug": "_3-3、基础操作指令"
        },
        {
          "level": 3,
          "title": "3.3.1、查看修改的状态（status）*",
          "slug": "_3-3-1、查看修改的状态-status"
        },
        {
          "level": 3,
          "title": "3.3.2、添加工作区到暂存区(add)*",
          "slug": "_3-3-2、添加工作区到暂存区-add"
        },
        {
          "level": 3,
          "title": "3.3.3、提交暂存区到本地仓库(commit)*",
          "slug": "_3-3-3、提交暂存区到本地仓库-commit"
        },
        {
          "level": 3,
          "title": "3.3.4、查看提交日志(log)*",
          "slug": "_3-3-4、查看提交日志-log"
        },
        {
          "level": 3,
          "title": "3.3.5、版本回退**",
          "slug": "_3-3-5、版本回退"
        },
        {
          "level": 3,
          "title": "3.3.6、添加文件至忽略列表**",
          "slug": "_3-3-6、添加文件至忽略列表"
        },
        {
          "level": 3,
          "title": "练习:基础操作",
          "slug": "练习-基础操作"
        },
        {
          "level": 2,
          "title": "3.4、分支",
          "slug": "_3-4、分支"
        },
        {
          "level": 3,
          "title": "3.4.1、查看本地分支",
          "slug": "_3-4-1、查看本地分支"
        },
        {
          "level": 3,
          "title": "3.4.2、创建本地分支",
          "slug": "_3-4-2、创建本地分支"
        },
        {
          "level": 3,
          "title": "3.4.4、切换分支(checkout)*",
          "slug": "_3-4-4、切换分支-checkout"
        },
        {
          "level": 3,
          "title": "3.4.6、合并分支(merge)*",
          "slug": "_3-4-6、合并分支-merge"
        },
        {
          "level": 3,
          "title": "3.4.7、删除分支*",
          "slug": "_3-4-7、删除分支"
        },
        {
          "level": 3,
          "title": "3.4.8、解决冲突",
          "slug": "_3-4-8、解决冲突"
        },
        {
          "level": 3,
          "title": "3.4.9、开发中分支使用原则与流程",
          "slug": "_3-4-9、开发中分支使用原则与流程"
        },
        {
          "level": 3,
          "title": "练习:分支操作",
          "slug": "练习-分支操作"
        },
        {
          "level": 2,
          "title": "4.1、常用的托管服务[远程仓库]",
          "slug": "_4-1、常用的托管服务-远程仓库"
        },
        {
          "level": 2,
          "title": "4.2、注册码云",
          "slug": "_4-2、注册码云"
        },
        {
          "level": 2,
          "title": "4.3、创建远程仓库",
          "slug": "_4-3、创建远程仓库"
        },
        {
          "level": 2,
          "title": "4.4、配置SSH公钥",
          "slug": "_4-4、配置ssh公钥"
        },
        {
          "level": 2,
          "title": "4.5.1、添加远程仓库",
          "slug": "_4-5-1、添加远程仓库"
        },
        {
          "level": 2,
          "title": "4.5.2、查看远程仓库",
          "slug": "_4-5-2、查看远程仓库"
        },
        {
          "level": 2,
          "title": "4.5.3、推送到远程仓库**",
          "slug": "_4-5-3、推送到远程仓库"
        },
        {
          "level": 2,
          "title": "4.5.4、本地分支与远程分支的关联关系**",
          "slug": "_4-5-4、本地分支与远程分支的关联关系"
        },
        {
          "level": 2,
          "title": "4.5.5、从远程仓库克隆*",
          "slug": "_4-5-5、从远程仓库克隆"
        },
        {
          "level": 2,
          "title": "4.5.6、从远程仓库中抓取和拉取*",
          "slug": "_4-5-6、从远程仓库中抓取和拉取"
        },
        {
          "level": 2,
          "title": "4.5.7、解决合并冲突",
          "slug": "_4-5-7、解决合并冲突"
        },
        {
          "level": 2,
          "title": "练习:远程仓库操作",
          "slug": "练习-远程仓库操作"
        },
        {
          "level": 2,
          "title": "5.1、在Idea中配置Git",
          "slug": "_5-1、在idea中配置git"
        },
        {
          "level": 2,
          "title": "5.2、在Idea中操作Git",
          "slug": "_5-2、在idea中操作git"
        },
        {
          "level": 3,
          "title": "5.2.1、创建项目远程仓库（参照4.3）",
          "slug": "_5-2-1、创建项目远程仓库-参照4-3"
        },
        {
          "level": 3,
          "title": "5.2.2、初始化本地仓库",
          "slug": "_5-2-2、初始化本地仓库"
        },
        {
          "level": 3,
          "title": "5.2.3、设置远程仓库",
          "slug": "_5-2-3、设置远程仓库"
        },
        {
          "level": 3,
          "title": "5.2.4、提交到本地仓库",
          "slug": "_5-2-4、提交到本地仓库"
        },
        {
          "level": 3,
          "title": "5.2.6、推送到远程仓库",
          "slug": "_5-2-6、推送到远程仓库"
        },
        {
          "level": 3,
          "title": "5.2.7、克隆远程仓库到本地",
          "slug": "_5-2-7、克隆远程仓库到本地"
        },
        {
          "level": 3,
          "title": "5.2.8、创建分支(强大的方式2)",
          "slug": "_5-2-8、创建分支-强大的方式2"
        },
        {
          "level": 3,
          "title": "5.2.9、切换分支及其他分支相关操作",
          "slug": "_5-2-9、切换分支及其他分支相关操作"
        },
        {
          "level": 3,
          "title": "5.2.11、解决冲突",
          "slug": "_5-2-11、解决冲突"
        },
        {
          "level": 2,
          "title": "5.3、IDEA常用GIT操作入口",
          "slug": "_5-3、idea常用git操作入口"
        },
        {
          "level": 2,
          "title": "5.4、场景分析",
          "slug": "_5-4、场景分析"
        }
      ],
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "Java",
      "frontmatter": {
        "title": "Java",
        "date": "2025-03-12T20:35:09.000Z",
        "permalink": "/InterviewQ/Java/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/02.Java.html",
      "relativePath": "04.InterviewQ/02.Java.md",
      "key": "v-cd328d1a",
      "path": "/InterviewQ/Java/",
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "INTV",
      "frontmatter": {
        "title": "INTV",
        "date": "2025-02-24T11:06:12.000Z",
        "permalink": "/InterviewQ/INTV/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/01.INTV.html",
      "relativePath": "04.InterviewQ/01.INTV.md",
      "key": "v-c739e29a",
      "path": "/InterviewQ/INTV/",
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "JUC",
      "frontmatter": {
        "title": "JUC",
        "date": "2025-03-21T16:26:41.000Z",
        "permalink": "/InterviewQ/JUC/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/03.JUC.html",
      "relativePath": "04.InterviewQ/03.JUC.md",
      "key": "v-071e3c0a",
      "path": "/InterviewQ/JUC/",
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "JVM",
      "frontmatter": {
        "title": "JVM",
        "date": "2025-03-03T09:58:58.000Z",
        "permalink": "/InterviewQ/JVM/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/04.JVM.html",
      "relativePath": "04.InterviewQ/04.JVM.md",
      "key": "v-e10f75b2",
      "path": "/InterviewQ/JVM/",
      "headers": [
        {
          "level": 2,
          "title": "OOM怎么解决",
          "slug": "oom怎么解决"
        },
        {
          "level": 2,
          "title": "jdk6-8内存区域的不同",
          "slug": "jdk6-8内存区域的不同"
        },
        {
          "level": 2,
          "title": "jvis",
          "slug": "jvis"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "Linux",
      "frontmatter": {
        "title": "Linux",
        "date": "2025-03-12T10:15:12.000Z",
        "permalink": "/InterviewQ/Linux/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/05.Linux.html",
      "relativePath": "04.InterviewQ/05.Linux.md",
      "key": "v-7904caff",
      "path": "/InterviewQ/Linux/",
      "headers": [
        {
          "level": 2,
          "title": "目录、文件",
          "slug": "目录、文件"
        },
        {
          "level": 3,
          "title": "查询日志文件后200条数据并实时监控",
          "slug": "查询日志文件后200条数据并实时监控"
        },
        {
          "level": 3,
          "title": "将文件中i改为I",
          "slug": "将文件中i改为i"
        },
        {
          "level": 2,
          "title": "系统",
          "slug": "系统"
        },
        {
          "level": 3,
          "title": "查看内存使用情况",
          "slug": "查看内存使用情况"
        },
        {
          "level": 3,
          "title": "修改用户权限",
          "slug": "修改用户权限"
        },
        {
          "level": 2,
          "title": "下载",
          "slug": "下载"
        },
        {
          "level": 2,
          "title": "使用 & 符号",
          "slug": "使用-符号"
        },
        {
          "level": 2,
          "title": "使用 nohup 命令",
          "slug": "使用-nohup-命令"
        },
        {
          "level": 2,
          "title": "使用 disown 命令",
          "slug": "使用-disown-命令"
        },
        {
          "level": 2,
          "title": "使用 jobs 命令",
          "slug": "使用-jobs-命令"
        },
        {
          "level": 2,
          "title": "使用 ps 命令",
          "slug": "使用-ps-命令"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "SQL",
      "frontmatter": {
        "title": "SQL",
        "date": "2025-03-08T09:27:40.000Z",
        "permalink": "/InterviewQ/SQL/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/06.SQL.html",
      "relativePath": "04.InterviewQ/06.SQL.md",
      "key": "v-210a26ee",
      "path": "/InterviewQ/SQL/",
      "headers": [
        {
          "level": 2,
          "title": "1. 如何定位慢查询",
          "slug": "_1-如何定位慢查询"
        },
        {
          "level": 2,
          "title": "2. 那这个SQL语句执行很慢，如何分析呢？",
          "slug": "_2-那这个sql语句执行很慢-如何分析呢"
        },
        {
          "level": 2,
          "title": "3. 了解过索引吗？（什么是索引）",
          "slug": "_3-了解过索引吗-什么是索引"
        },
        {
          "level": 2,
          "title": "4. 索引的底层数据结构了解过吗？",
          "slug": "_4-索引的底层数据结构了解过吗"
        },
        {
          "level": 2,
          "title": "5. B树和B+树的区别是什么呢？",
          "slug": "_5-b树和b-树的区别是什么呢"
        },
        {
          "level": 2,
          "title": "6. 什么是聚簇索引什么是非聚簇索引？",
          "slug": "_6-什么是聚簇索引什么是非聚簇索引"
        },
        {
          "level": 2,
          "title": "7. 知道什么是回表查询吗？",
          "slug": "_7-知道什么是回表查询吗"
        },
        {
          "level": 2,
          "title": "8. 知道什么叫覆盖索引吗？",
          "slug": "_8-知道什么叫覆盖索引吗"
        },
        {
          "level": 2,
          "title": "9. MySQL超大分页怎么处理？",
          "slug": "_9-mysql超大分页怎么处理"
        },
        {
          "level": 2,
          "title": "10. 索引创建原则有哪些？",
          "slug": "_10-索引创建原则有哪些"
        },
        {
          "level": 2,
          "title": "11. 什么情况下索引会失效？",
          "slug": "_11-什么情况下索引会失效"
        },
        {
          "level": 2,
          "title": "12. SQL的优化经验有哪些？",
          "slug": "_12-sql的优化经验有哪些"
        },
        {
          "level": 2,
          "title": "13. 创建表的时候，你们是如何优化的呢？",
          "slug": "_13-创建表的时候-你们是如何优化的呢"
        },
        {
          "level": 2,
          "title": "14. 在使用索引的时候，是如何优化呢？",
          "slug": "_14-在使用索引的时候-是如何优化呢"
        },
        {
          "level": 2,
          "title": "15. 你平时对SQL语句做了哪些优化呢？",
          "slug": "_15-你平时对sql语句做了哪些优化呢"
        },
        {
          "level": 2,
          "title": "16. 事务的特性是什么？可以详细说一下吗？",
          "slug": "_16-事务的特性是什么-可以详细说一下吗"
        },
        {
          "level": 2,
          "title": "17. 并发事务带来哪些问题？",
          "slug": "_17-并发事务带来哪些问题"
        },
        {
          "level": 2,
          "title": "18. 怎么解决这些问题呢？MySQL的默认隔离级别是？",
          "slug": "_18-怎么解决这些问题呢-mysql的默认隔离级别是"
        },
        {
          "level": 2,
          "title": "19. undo log和redo log的区别是什么？",
          "slug": "_19-undo-log和redo-log的区别是什么"
        },
        {
          "level": 2,
          "title": "20. 事务中的隔离性是如何保证的呢？（你解释一下MVCC）",
          "slug": "_20-事务中的隔离性是如何保证的呢-你解释一下mvcc"
        },
        {
          "level": 2,
          "title": "21. MySQL主从同步原理是什么？",
          "slug": "_21-mysql主从同步原理是什么"
        },
        {
          "level": 2,
          "title": "22. 你们项目用过MySQL的分库分表吗？",
          "slug": "_22-你们项目用过mysql的分库分表吗"
        },
        {
          "level": 2,
          "title": "23. 那你之前使用过水平分库吗？",
          "slug": "_23-那你之前使用过水平分库吗"
        },
        {
          "level": 2,
          "title": "为什么update一定要用索引",
          "slug": "为什么update一定要用索引"
        }
      ],
      "lastUpdated": "2025/3/28 16:39:28",
      "lastUpdatedTimestamp": 1743151168000
    },
    {
      "title": "Maven",
      "frontmatter": {
        "title": "Maven",
        "date": "2025-03-18T09:29:53.000Z",
        "permalink": "/InterviewQ/Maven/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/07.Maven.html",
      "relativePath": "04.InterviewQ/07.Maven.md",
      "key": "v-73e1a14d",
      "path": "/InterviewQ/Maven/",
      "headers": [
        {
          "level": 2,
          "title": "1.什么是 Maven？它的作用是什么？",
          "slug": "_1-什么是-maven-它的作用是什么"
        },
        {
          "level": 2,
          "title": "2.Maven 的生命周期",
          "slug": "_2-maven-的生命周期"
        },
        {
          "level": 2,
          "title": "3. maven指令",
          "slug": "_3-maven指令"
        },
        {
          "level": 2,
          "title": "4. Maven 的依赖范围（Dependency Scope）有哪些？",
          "slug": "_4-maven-的依赖范围-dependency-scope-有哪些"
        },
        {
          "level": 2,
          "title": "5. Maven 如何解决依赖冲突？",
          "slug": "_5-maven-如何解决依赖冲突"
        },
        {
          "level": 2,
          "title": "6. 如何排除依赖中的某个传递性依赖？",
          "slug": "_6-如何排除依赖中的某个传递性依赖"
        },
        {
          "level": 2,
          "title": "7. Maven 的仓库有哪些类型？",
          "slug": "_7-maven-的仓库有哪些类型"
        },
        {
          "level": 2,
          "title": "8. 如何将项目部署到远程仓库？",
          "slug": "_8-如何将项目部署到远程仓库"
        },
        {
          "level": 2,
          "title": "10. 如何跳过测试？",
          "slug": "_10-如何跳过测试"
        },
        {
          "level": 2,
          "title": "11. 什么是 Maven Profile？它的作用是什么？",
          "slug": "_11-什么是-maven-profile-它的作用是什么"
        },
        {
          "level": 2,
          "title": "12. 如何查看项目的依赖树？",
          "slug": "_12-如何查看项目的依赖树"
        },
        {
          "level": 2,
          "title": "13. Maven 的聚合（Aggregation）和继承（Inheritance）有什么区别？",
          "slug": "_13-maven-的聚合-aggregation-和继承-inheritance-有什么区别"
        },
        {
          "level": 2,
          "title": "14. 如何自定义 Maven 构建的输出目录？",
          "slug": "_14-如何自定义-maven-构建的输出目录"
        },
        {
          "level": 2,
          "title": "15. Maven 的 Snapshot 版本和 Release 版本有什么区别？",
          "slug": "_15-maven-的-snapshot-版本和-release-版本有什么区别"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "MyBatis",
      "frontmatter": {
        "title": "MyBatis",
        "date": "2025-03-12T09:10:38.000Z",
        "permalink": "/InterviewQ/MyBatis/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/08.MyBatis.html",
      "relativePath": "04.InterviewQ/08.MyBatis.md",
      "key": "v-4416917b",
      "path": "/InterviewQ/MyBatis/",
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "SpringHome",
      "frontmatter": {
        "title": "SpringHome",
        "date": "2025-03-11T17:51:14.000Z",
        "permalink": "/pages/896da2/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/09.SpringHome.html",
      "relativePath": "04.InterviewQ/09.SpringHome.md",
      "key": "v-4fb26793",
      "path": "/pages/896da2/",
      "headers": [
        {
          "level": 2,
          "title": "怎么组织上面这些对象的转换，有没有遇到什么挑战",
          "slug": "怎么组织上面这些对象的转换-有没有遇到什么挑战"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "Algorithm",
      "frontmatter": {
        "title": "Algorithm",
        "date": "2025-03-11T21:14:31.000Z",
        "permalink": "/InterviewQ/Algorithm/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/11.Algorithm.html",
      "relativePath": "04.InterviewQ/11.Algorithm.md",
      "key": "v-d917335a",
      "path": "/InterviewQ/Algorithm/",
      "headers": [
        {
          "level": 3,
          "title": "前缀和",
          "slug": "前缀和"
        },
        {
          "level": 3,
          "title": "哈希表",
          "slug": "哈希表"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "Redis",
      "frontmatter": {
        "title": "Redis",
        "date": "2025-03-14T15:19:32.000Z",
        "permalink": "/InterviewQ/Redis/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/10.Redis.html",
      "relativePath": "04.InterviewQ/10.Redis.md",
      "key": "v-25c8413d",
      "path": "/InterviewQ/Redis/",
      "headers": [
        {
          "level": 2,
          "title": "5. redis作为缓存，如何保证redis与mysql数据的同步",
          "slug": "_5-redis作为缓存-如何保证redis与mysql数据的同步"
        },
        {
          "level": 2,
          "title": "6. 那这个排他锁是如何保证读写、读读互斥的呢？",
          "slug": "_6-那这个排他锁是如何保证读写、读读互斥的呢"
        },
        {
          "level": 2,
          "title": "7. 你听说过延时双删吗？为什么不用它呢？",
          "slug": "_7-你听说过延时双删吗-为什么不用它呢"
        },
        {
          "level": 2,
          "title": "8. redis作为缓存，如何保证redis与mysql数据的同步",
          "slug": "_8-redis作为缓存-如何保证redis与mysql数据的同步"
        },
        {
          "level": 2,
          "title": "10. 这两种持久化方式有什么区别呢？",
          "slug": "_10-这两种持久化方式有什么区别呢"
        },
        {
          "level": 2,
          "title": "11. 这两种方式，哪种恢复的比较快呢？",
          "slug": "_11-这两种方式-哪种恢复的比较快呢"
        },
        {
          "level": 2,
          "title": "RDB的执行原理",
          "slug": "rdb的执行原理"
        },
        {
          "level": 2,
          "title": "14. 数据库有1000万数据，Redis只能缓存20w数据。如何保证Redis中的数据都是热点数据？",
          "slug": "_14-数据库有1000万数据-redis只能缓存20w数据。如何保证redis中的数据都是热点数据"
        },
        {
          "level": 2,
          "title": "15. Redis的内存用完了会发生什么？",
          "slug": "_15-redis的内存用完了会发生什么"
        },
        {
          "level": 2,
          "title": "17. Redis实现分布式锁如何合理的控制锁的有效时长",
          "slug": "_17-redis实现分布式锁如何合理的控制锁的有效时长"
        },
        {
          "level": 2,
          "title": "18. Redisson实现的分布式锁是可重入的吗？",
          "slug": "_18-redisson实现的分布式锁是可重入的吗"
        },
        {
          "level": 2,
          "title": "19. Redisson实现的分布式锁能解决主从一致性的问题吗？",
          "slug": "_19-redisson实现的分布式锁能解决主从一致性的问题吗"
        },
        {
          "level": 2,
          "title": "20. 如果业务非要保证数据的强一致性，这个该怎么解决呢？",
          "slug": "_20-如果业务非要保证数据的强一致性-这个该怎么解决呢"
        },
        {
          "level": 2,
          "title": "23. 能说一下，主从同步数据的流程吗？",
          "slug": "_23-能说一下-主从同步数据的流程吗"
        },
        {
          "level": 2,
          "title": "25. 你们使用Redis是单点还是集群，哪种集群？",
          "slug": "_25-你们使用redis是单点还是集群-哪种集群"
        },
        {
          "level": 2,
          "title": "26. Redis集群脑裂，该怎么解决呢？",
          "slug": "_26-redis集群脑裂-该怎么解决呢"
        },
        {
          "level": 2,
          "title": "28. Redis分片集群中数据是怎么存储和读取的？",
          "slug": "_28-redis分片集群中数据是怎么存储和读取的"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "Login",
      "frontmatter": {
        "title": "Login",
        "date": "2025-03-11T17:45:45.000Z",
        "permalink": "/InterviewQ/Login/",
        "categories": [
          "InterviewQ"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/04.InterviewQ/12.Login.html",
      "relativePath": "04.InterviewQ/12.Login.md",
      "key": "v-dd6c0f46",
      "path": "/InterviewQ/Login/",
      "headers": [
        {
          "level": 2,
          "title": "扫码登录的实现原理",
          "slug": "扫码登录的实现原理"
        },
        {
          "level": 2,
          "title": "如何使用redis记录上亿用户连续登录天数？",
          "slug": "如何使用redis记录上亿用户连续登录天数"
        },
        {
          "level": 2,
          "title": "session、token、redis、nginx",
          "slug": "session、token、redis、nginx"
        },
        {
          "level": 2,
          "title": "session",
          "slug": "session"
        },
        {
          "level": 3,
          "title": "session+redis",
          "slug": "session-redis"
        },
        {
          "level": 3,
          "title": "为什么没有使用nginx+session的方案",
          "slug": "为什么没有使用nginx-session的方案"
        },
        {
          "level": 2,
          "title": "token",
          "slug": "token"
        },
        {
          "level": 2,
          "title": "JWT",
          "slug": "jwt"
        },
        {
          "level": 3,
          "title": "如何实现双 Token 机制？它的优点是什么？",
          "slug": "如何实现双-token-机制-它的优点是什么"
        },
        {
          "level": 3,
          "title": "如何实现单点登录（SSO）？Session 和 Token 在 SSO 中分别如何应用？",
          "slug": "如何实现单点登录-sso-session-和-token-在-sso-中分别如何应用"
        },
        {
          "level": 3,
          "title": "JWT的滑动过期机制",
          "slug": "jwt的滑动过期机制"
        },
        {
          "level": 3,
          "title": "在分布式系统中如何处理JWT的滑动过期",
          "slug": "在分布式系统中如何处理jwt的滑动过期"
        },
        {
          "level": 3,
          "title": "Redis + Token 和 JWT 的区别",
          "slug": "redis-token-和-jwt-的区别"
        },
        {
          "level": 3,
          "title": "Session 和 Token 可以结合使用吗？如果可以，如何实现？",
          "slug": "session-和-token-可以结合使用吗-如果可以-如何实现"
        },
        {
          "level": 2,
          "title": "Cookie、Session、JWT",
          "slug": "cookie、session、jwt"
        },
        {
          "level": 3,
          "title": "Session 和 Token 分别有哪些安全性问题？如何解决？",
          "slug": "session-和-token-分别有哪些安全性问题-如何解决"
        },
        {
          "level": 3,
          "title": "在选择将JWT存储在LocalStorage还是Cookie时，你认为哪种方式更好？为什么？",
          "slug": "在选择将jwt存储在localstorage还是cookie时-你认为哪种方式更好-为什么"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "Java",
      "frontmatter": {
        "title": "Java",
        "date": "2025-02-09T22:38:09.000Z",
        "permalink": "/pages/5f620a/",
        "categories": [
          "Java"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/05.Java/01.Java.html",
      "relativePath": "05.Java/01.Java.md",
      "key": "v-a8b7029a",
      "path": "/pages/5f620a/",
      "headers": [
        {
          "level": 2,
          "title": "分页",
          "slug": "分页"
        },
        {
          "level": 2,
          "title": "Mybatis映射文件动态sql",
          "slug": "mybatis映射文件动态sql"
        },
        {
          "level": 2,
          "title": "removeByIds和removeBatchByIds",
          "slug": "removebyids和removebatchbyids"
        },
        {
          "level": 2,
          "title": "# 批量新增",
          "slug": "批量新增"
        },
        {
          "level": 2,
          "title": "循环依赖DB静态工具",
          "slug": "循环依赖db静态工具"
        },
        {
          "level": 2,
          "title": "逻辑删除",
          "slug": "逻辑删除"
        },
        {
          "level": 2,
          "title": "枚举处理器",
          "slug": "枚举处理器"
        },
        {
          "level": 3,
          "title": "配置枚举处理器",
          "slug": "配置枚举处理器"
        },
        {
          "level": 3,
          "title": "定义枚举",
          "slug": "定义枚举"
        },
        {
          "level": 2,
          "title": "Json类型处理器",
          "slug": "json类型处理器"
        },
        {
          "level": 2,
          "title": "分页插件",
          "slug": "分页插件"
        },
        {
          "level": 2,
          "title": "lambda表达式",
          "slug": "lambda表达式"
        },
        {
          "level": 2,
          "title": "链式编程",
          "slug": "链式编程"
        },
        {
          "level": 3,
          "title": "Build",
          "slug": "build"
        },
        {
          "level": 2,
          "title": "函数式接口（四种）",
          "slug": "函数式接口-四种"
        },
        {
          "level": 3,
          "title": "Function函数型接口",
          "slug": "function函数型接口"
        },
        {
          "level": 3,
          "title": "Predicate断定型接口",
          "slug": "predicate断定型接口"
        },
        {
          "level": 3,
          "title": "Consumer消费型接口",
          "slug": "consumer消费型接口"
        },
        {
          "level": 3,
          "title": "supplier供给型接口",
          "slug": "supplier供给型接口"
        },
        {
          "level": 2,
          "title": "Stream流式计算",
          "slug": "stream流式计算"
        }
      ],
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "JVM",
      "frontmatter": {
        "title": "JVM",
        "date": "2025-02-09T15:54:05.000Z",
        "permalink": "/pages/777f5e/",
        "categories": [
          "Java"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/05.Java/03.JVM.html",
      "relativePath": "05.Java/03.JVM.md",
      "key": "v-417f3b4b",
      "path": "/pages/777f5e/",
      "headers": [
        {
          "level": 2,
          "title": "方法区的回收",
          "slug": "方法区的回收"
        },
        {
          "level": 2,
          "title": "引用计数法",
          "slug": "引用计数法"
        },
        {
          "level": 3,
          "title": "可达性分析算法",
          "slug": "可达性分析算法"
        },
        {
          "level": 2,
          "title": "几种常见的对象引用",
          "slug": "几种常见的对象引用"
        },
        {
          "level": 3,
          "title": "软引用",
          "slug": "软引用"
        },
        {
          "level": 3,
          "title": "弱引用",
          "slug": "弱引用"
        },
        {
          "level": 3,
          "title": "虚引用和终结器引用",
          "slug": "虚引用和终结器引用"
        },
        {
          "level": 2,
          "title": "垃圾回收算法-核心思想",
          "slug": "垃圾回收算法-核心思想"
        },
        {
          "level": 2,
          "title": "垃圾回收算法的评价标准",
          "slug": "垃圾回收算法的评价标准"
        },
        {
          "level": 2,
          "title": "垃圾回收算法-标记清除算法",
          "slug": "垃圾回收算法-标记清除算法"
        },
        {
          "level": 2,
          "title": "五种invoke方法",
          "slug": "五种invoke方法"
        }
      ],
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "反射&动态代理",
      "frontmatter": {
        "title": "反射&动态代理",
        "date": "2025-02-10T23:21:57.000Z",
        "permalink": "/pages/6d69d7/",
        "categories": [
          "Java"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/05.Java/04.%E5%8F%8D%E5%B0%84&%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86.html",
      "relativePath": "05.Java/04.反射&动态代理.md",
      "key": "v-5059f7fe",
      "path": "/pages/6d69d7/",
      "headers": [
        {
          "level": 2,
          "title": "1.1 反射的概述：",
          "slug": "_1-1-反射的概述"
        },
        {
          "level": 2,
          "title": "1.2 学习反射到底学什么？",
          "slug": "_1-2-学习反射到底学什么"
        },
        {
          "level": 2,
          "title": "1.3 获取字节码文件对象的三种方式**",
          "slug": "_1-3-获取字节码文件对象的三种方式"
        },
        {
          "level": 2,
          "title": "1.4 字节码文件和字节码文件对象",
          "slug": "_1-4-字节码文件和字节码文件对象"
        },
        {
          "level": 2,
          "title": "1.5 获取构造方法**",
          "slug": "_1-5-获取构造方法"
        },
        {
          "level": 2,
          "title": "1.6 获取构造方法并创建对象**",
          "slug": "_1-6-获取构造方法并创建对象"
        },
        {
          "level": 2,
          "title": "1.7 获取成员变量",
          "slug": "_1-7-获取成员变量"
        },
        {
          "level": 2,
          "title": "1.8 获取成员变量并获取值和修改值",
          "slug": "_1-8-获取成员变量并获取值和修改值"
        },
        {
          "level": 2,
          "title": "1.9 获取成员方法",
          "slug": "_1-9-获取成员方法"
        },
        {
          "level": 2,
          "title": "1.10 获取成员方法并运行",
          "slug": "_1-10-获取成员方法并运行"
        },
        {
          "level": 2,
          "title": "面试题：",
          "slug": "面试题"
        },
        {
          "level": 2,
          "title": "1.11 练习泛型擦除（掌握概念，了解代码）",
          "slug": "_1-11-练习泛型擦除-掌握概念-了解代码"
        },
        {
          "level": 2,
          "title": "1.12 练习：修改字符串的内容（掌握概念，了解代码）",
          "slug": "_1-12-练习-修改字符串的内容-掌握概念-了解代码"
        },
        {
          "level": 2,
          "title": "1.13 练习，反射和配置文件结合动态获取的练习（重点）",
          "slug": "_1-13-练习-反射和配置文件结合动态获取的练习-重点"
        },
        {
          "level": 2,
          "title": "1.14 利用发射保存对象中的信息（重点）",
          "slug": "_1-14-利用发射保存对象中的信息-重点"
        },
        {
          "level": 2,
          "title": "2.1 好处：",
          "slug": "_2-1-好处"
        },
        {
          "level": 2,
          "title": "2.2 动态代理三要素：",
          "slug": "_2-2-动态代理三要素"
        },
        {
          "level": 2,
          "title": "2.3 代码实现：",
          "slug": "_2-3-代码实现"
        },
        {
          "level": 2,
          "title": "2.4 额外扩展",
          "slug": "_2-4-额外扩展"
        },
        {
          "level": 2,
          "title": "2.5 动态代理的练习**",
          "slug": "_2-5-动态代理的练习"
        }
      ],
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "Learn",
      "frontmatter": {
        "title": "Learn",
        "date": "2025-03-22T16:03:49.000Z",
        "permalink": "/pages/c70e3b/",
        "categories": [
          "Learn"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/06.Learn/01.Learn.html",
      "relativePath": "06.Learn/01.Learn.md",
      "key": "v-eedbe766",
      "path": "/pages/c70e3b/",
      "headers": [
        {
          "level": 2,
          "title": "幸福只属于知足的人",
          "slug": "幸福只属于知足的人"
        }
      ],
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    },
    {
      "title": "JUC",
      "frontmatter": {
        "title": "JUC",
        "date": "2025-02-09T15:54:11.000Z",
        "permalink": "/pages/eec04e/",
        "categories": [
          "Java"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/05.Java/02.JUC.html",
      "relativePath": "05.Java/02.JUC.md",
      "key": "v-8ba3a0c2",
      "path": "/pages/eec04e/",
      "headers": [
        {
          "level": 2,
          "title": "Callable",
          "slug": "callable"
        },
        {
          "level": 2,
          "title": "Synchronized",
          "slug": "synchronized"
        },
        {
          "level": 3,
          "title": "管程monitor",
          "slug": "管程monitor"
        },
        {
          "level": 3,
          "title": "轻量级锁和重量级锁",
          "slug": "轻量级锁和重量级锁"
        },
        {
          "level": 3,
          "title": "锁膨胀",
          "slug": "锁膨胀"
        },
        {
          "level": 3,
          "title": "自旋优化",
          "slug": "自旋优化"
        },
        {
          "level": 3,
          "title": "偏向锁",
          "slug": "偏向锁"
        },
        {
          "level": 3,
          "title": "锁粗化",
          "slug": "锁粗化"
        },
        {
          "level": 3,
          "title": "锁消除",
          "slug": "锁消除"
        },
        {
          "level": 3,
          "title": "wait、notify(必须获得锁对象synchronized才能调用)",
          "slug": "wait、notify-必须获得锁对象synchronized才能调用"
        },
        {
          "level": 3,
          "title": "wait/sleep 区别⭐",
          "slug": "wait-sleep-区别⭐"
        },
        {
          "level": 3,
          "title": "防止虚假唤醒⭐",
          "slug": "防止虚假唤醒⭐"
        },
        {
          "level": 3,
          "title": "死锁、活锁",
          "slug": "死锁、活锁"
        },
        {
          "level": 2,
          "title": "Lock 接口",
          "slug": "lock-接口"
        },
        {
          "level": 2,
          "title": "Synchronized 和 Lock 区别⭐",
          "slug": "synchronized-和-lock-区别⭐"
        },
        {
          "level": 2,
          "title": "synchronized和lock的区别",
          "slug": "synchronized和lock的区别"
        },
        {
          "level": 2,
          "title": "生产者和消费者问题",
          "slug": "生产者和消费者问题"
        },
        {
          "level": 3,
          "title": "Synchronized",
          "slug": "synchronized-2"
        },
        {
          "level": 3,
          "title": "JUC",
          "slug": "juc"
        },
        {
          "level": 3,
          "title": "JUC版的生产者和消费者问题",
          "slug": "juc版的生产者和消费者问题"
        },
        {
          "level": 2,
          "title": "8锁现象",
          "slug": "_8锁现象"
        },
        {
          "level": 2,
          "title": "ConcurrentModificationException⭐",
          "slug": "concurrentmodificationexception⭐"
        },
        {
          "level": 2,
          "title": "List 不安全",
          "slug": "list-不安全"
        },
        {
          "level": 3,
          "title": "解决方案",
          "slug": "解决方案"
        },
        {
          "level": 2,
          "title": "Set不安全",
          "slug": "set不安全"
        },
        {
          "level": 3,
          "title": "解决方案",
          "slug": "解决方案-2"
        },
        {
          "level": 3,
          "title": "HashSet底层是什么？",
          "slug": "hashset底层是什么"
        },
        {
          "level": 2,
          "title": "HashMap不安全",
          "slug": "hashmap不安全"
        },
        {
          "level": 3,
          "title": "解决方案",
          "slug": "解决方案-3"
        },
        {
          "level": 2,
          "title": "CountDownLatch",
          "slug": "countdownlatch"
        },
        {
          "level": 2,
          "title": "CyclicBarrier",
          "slug": "cyclicbarrier"
        },
        {
          "level": 2,
          "title": "Semaphore",
          "slug": "semaphore"
        },
        {
          "level": 2,
          "title": "ReadWriteLock",
          "slug": "readwritelock"
        },
        {
          "level": 2,
          "title": "BlockingQueue",
          "slug": "blockingqueue"
        },
        {
          "level": 3,
          "title": "会抛出异常",
          "slug": "会抛出异常"
        },
        {
          "level": 3,
          "title": "有返回值 不会抛出异常",
          "slug": "有返回值-不会抛出异常"
        },
        {
          "level": 3,
          "title": "检测队首元素",
          "slug": "检测队首元素"
        },
        {
          "level": 3,
          "title": "等待 阻塞",
          "slug": "等待-阻塞"
        },
        {
          "level": 3,
          "title": "超时等待 自动退出",
          "slug": "超时等待-自动退出"
        },
        {
          "level": 2,
          "title": "SynchronizedQueue",
          "slug": "synchronizedqueue"
        },
        {
          "level": 2,
          "title": "execute",
          "slug": "execute"
        },
        {
          "level": 2,
          "title": "submit",
          "slug": "submit"
        },
        {
          "level": 2,
          "title": "三个方法",
          "slug": "三个方法"
        },
        {
          "level": 2,
          "title": "七大参数",
          "slug": "七大参数"
        },
        {
          "level": 2,
          "title": "四种拒绝策略",
          "slug": "四种拒绝策略"
        },
        {
          "level": 2,
          "title": "Function函数式接口",
          "slug": "function函数式接口"
        },
        {
          "level": 2,
          "title": "断定型接口",
          "slug": "断定型接口"
        },
        {
          "level": 2,
          "title": "Consumer 消费型接口",
          "slug": "consumer-消费型接口"
        },
        {
          "level": 2,
          "title": "Supplier 供给型接口",
          "slug": "supplier-供给型接口"
        },
        {
          "level": 2,
          "title": "CompletableFuture",
          "slug": "completablefuture"
        },
        {
          "level": 3,
          "title": "runAsync",
          "slug": "runasync"
        },
        {
          "level": 3,
          "title": "SupplyAsync",
          "slug": "supplyasync"
        },
        {
          "level": 2,
          "title": "内存交互操作",
          "slug": "内存交互操作"
        },
        {
          "level": 2,
          "title": "保证可见性",
          "slug": "保证可见性"
        },
        {
          "level": 3,
          "title": "synchronized",
          "slug": "synchronized-3"
        },
        {
          "level": 2,
          "title": "不保证原子性",
          "slug": "不保证原子性"
        },
        {
          "level": 2,
          "title": "指令重排",
          "slug": "指令重排"
        },
        {
          "level": 3,
          "title": "内存屏障",
          "slug": "内存屏障"
        },
        {
          "level": 3,
          "title": "volatile",
          "slug": "volatile"
        },
        {
          "level": 3,
          "title": "synchronized",
          "slug": "synchronized-4"
        },
        {
          "level": 2,
          "title": "饿汉式",
          "slug": "饿汉式"
        },
        {
          "level": 2,
          "title": "DCL 懒汉式",
          "slug": "dcl-懒汉式"
        },
        {
          "level": 2,
          "title": "DCL 需要volatile",
          "slug": "dcl-需要volatile"
        },
        {
          "level": 2,
          "title": "静态内部类",
          "slug": "静态内部类"
        },
        {
          "level": 2,
          "title": "枚举",
          "slug": "枚举"
        },
        {
          "level": 2,
          "title": "什么是 CAS",
          "slug": "什么是-cas"
        },
        {
          "level": 2,
          "title": "Unsafe 类",
          "slug": "unsafe-类"
        },
        {
          "level": 2,
          "title": "公平锁、非公平锁",
          "slug": "公平锁、非公平锁"
        },
        {
          "level": 2,
          "title": "可重入锁",
          "slug": "可重入锁"
        },
        {
          "level": 3,
          "title": "Synchronized版",
          "slug": "synchronized版"
        },
        {
          "level": 3,
          "title": "Lock 版",
          "slug": "lock-版"
        },
        {
          "level": 2,
          "title": "自旋锁",
          "slug": "自旋锁"
        },
        {
          "level": 2,
          "title": "死锁⭐",
          "slug": "死锁⭐"
        }
      ],
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "Linux",
      "frontmatter": {
        "title": "Linux",
        "date": "2025-03-19T10:32:42.000Z",
        "permalink": "/pages/29ecf5/",
        "categories": [
          "Linux"
        ],
        "tags": [
          null
        ],
        "readingShow": "top"
      },
      "regularPath": "/07.Linux/01.Linux.html",
      "relativePath": "07.Linux/01.Linux.md",
      "key": "v-3c0876ed",
      "path": "/pages/29ecf5/",
      "headers": [
        {
          "level": 2,
          "title": "修改用户权限",
          "slug": "修改用户权限"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ],
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false,
        "readingShow": "top"
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-d1ba87a6",
      "path": "/archives/",
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false,
        "readingShow": "top"
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-0343b8e6",
      "path": "/categories/",
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false,
        "readingShow": "top"
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-75116ca6",
      "path": "/tags/",
      "lastUpdated": "2025/3/28 10:23:05",
      "lastUpdatedTimestamp": 1743128585000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://img.cyanyep.top/Blog/Snipaste_2025-02-11_20-04-18.png",
        "heroText": "西螈的博客",
        "tagline": "Hero副标题",
        "actionText": "快速上手→",
        "actionLink": "/README.md",
        "features": [
          {
            "title": "简洁至上",
            "details": "以Markdown为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受Vue+ webpack 的开发体验，在Markdown中使用Vue组件，同时可以使用Vue来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。",
            "footer": "粤ICP备2022067627号-1  粤公网安备 44011302003646号"
          }
        ],
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-63e8a84a",
      "path": "/",
      "lastUpdated": "2025/3/28 15:14:15",
      "lastUpdatedTimestamp": 1743146055000
    }
  ],
  "themeConfig": {
    "logo": "https://img.cyanyep.top/Blog/Snipaste_2025-02-11_20-04-18.png",
    "lastUpdated": "上次更新",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "西螈的 JavaScript 博客",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/cyanyep"
          },
          {
            "text": "CSDN",
            "link": "https://blog.csdn.net/rc4gyyc"
          }
        ]
      },
      {
        "text": "Java",
        "items": [
          {
            "text": "Java",
            "link": "https://github.com/cyanyep"
          },
          {
            "text": "Spring",
            "link": "https://blog.csdn.net/rc4gyyc"
          }
        ]
      }
    ],
    "sidebar": {
      "/01.Blog/": [
        [
          "01.Introduce.md",
          "零成本搭建个人博客网站",
          "/Blog/Introduce/"
        ],
        [
          "02.Build.md",
          "从零开始搭建博客",
          "/Blog/build/"
        ],
        [
          "03.More.md",
          "更多配置",
          "/Blog/More/"
        ],
        [
          "04.DN.md",
          "域名",
          "/Blog/DN/"
        ],
        [
          "05.Qiniu.md",
          "图床",
          "/Blog/Qiniu/"
        ],
        [
          "06.Sync.md",
          "同步GitHub和Gitee",
          "/Blog/Sync/"
        ],
        [
          "07.AutoDeploy.md",
          "自动部署",
          "/Blog/AutoDeploy/"
        ]
      ],
      "catalogue": {},
      "/02.C++/": [
        [
          "01.C++方法.md",
          "C++方法",
          "/pages/f8a36c/"
        ]
      ],
      "/03.Git/": [
        [
          "01.Git.md",
          "Git",
          "/pages/2e662a/"
        ]
      ],
      "/04.InterviewQ/": [
        [
          "01.INTV.md",
          "INTV",
          "/InterviewQ/INTV/"
        ],
        [
          "02.Java.md",
          "Java",
          "/InterviewQ/Java/"
        ],
        [
          "03.JUC.md",
          "JUC",
          "/InterviewQ/JUC/"
        ],
        [
          "04.JVM.md",
          "JVM",
          "/InterviewQ/JVM/"
        ],
        [
          "05.Linux.md",
          "Linux",
          "/InterviewQ/Linux/"
        ],
        [
          "06.SQL.md",
          "SQL",
          "/InterviewQ/SQL/"
        ],
        [
          "07.Maven.md",
          "Maven",
          "/InterviewQ/Maven/"
        ],
        [
          "08.MyBatis.md",
          "MyBatis",
          "/InterviewQ/MyBatis/"
        ],
        [
          "09.SpringHome.md",
          "SpringHome",
          "/pages/896da2/"
        ],
        [
          "10.Redis.md",
          "Redis",
          "/InterviewQ/Redis/"
        ],
        [
          "11.Algorithm.md",
          "Algorithm",
          "/InterviewQ/Algorithm/"
        ],
        [
          "12.Login.md",
          "Login",
          "/InterviewQ/Login/"
        ]
      ],
      "/05.Java/": [
        [
          "01.Java.md",
          "Java",
          "/pages/5f620a/"
        ],
        [
          "02.JUC.md",
          "JUC",
          "/pages/eec04e/"
        ],
        [
          "03.JVM.md",
          "JVM",
          "/pages/777f5e/"
        ],
        [
          "04.反射&动态代理.md",
          "反射&动态代理",
          "/pages/6d69d7/"
        ]
      ],
      "/06.Learn/": [
        [
          "01.Learn.md",
          "Learn",
          "/pages/c70e3b/"
        ]
      ],
      "/07.Linux/": [
        [
          "01.Linux.md",
          "Linux",
          "/pages/29ecf5/"
        ]
      ]
    },
    "repo": "vuejs/vuepress",
    "editLinks": true,
    "docsDir": "docs",
    "editLinkText": "在GitHub编辑此页",
    "footer": {
      "createYear": 2022
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}