name: Deploy VuePress to GitHub Pages
# 当 pages-code 分支有 push 事件时触发
on:
  push:
    branches:
      - pages-code
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 使用action库，安装node
      - name: Set up Node.js  # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 根据你的项目需求选择 Node.js 版本

      # 缓存 node_modules
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules #表示要缓存项目的 node_modules 文件夹
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

     # 安装依赖（仅在缓存未命中时执行）
      - name: npm install 
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install 

      # 构建 VuePress 项目，并将workflow拷贝到dist中用于仓库同步到gitee
      - name: Build VuePress
        run: |
          npm run docs:build
          ls -la ./docs/.vuepress/dist/  

      # 复制同步工作流syncToGitee 到 dist
      - name: Copy .github to dist
        run: |
          mkdir -p ./docs/.vuepress/dist/.github/workflows
          cp ./.github/workflows/syncToGitee.yml ./docs/.vuepress/dist/.github/workflows/
          ls -la ./docs/.vuepress/dist/.github
        # 检查是否复制成功


      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }} # 自动提供的 GitHub Token
          publish_dir: ./docs/.vuepress/dist # VuePress 默认的输出目录
          publish_branch: cy-pages # 部署到的目标分支
          exclude_assets: ""


#      #部署到服务器
#      - name: Deploy to Staging My server
#        uses: easingthemes/ssh-deploy@v2.1.6
#        env:
#          # 使用GitHub仓库里的secret设置的值
#          SSH_PRIVATE_KEY: ${{ secrets.MY_SERVER_PRIVATE_KEY }} 
#          # 源目录，编译后生成的文件目录
#          SOURCE: './docs/.vuepress/dist/'
#          #服务器公网地址
#          REMOTE_HOST: ${{ secrets.MY_SERVER_IP }}
#          #服务器用户名-一般默认root
#          REMOTE_USER: 'root'
#          #服务器中，代码部署的位置
#          TARGET: '/opt/myblog'
#          #去除的文件
#          EXCLUDE: "/dist/, /node_modules/" 